#---------------------------
# Material-T
# Author: rook1e
# Github: https://github.com/0x2e/Material-T
#---------------------------

#---------------------------
# 全局
# Site
#---------------------------
favicon: /favicon.png
apple_touch_icon: /apple-touch-icon.png


#---------------------------
# 首页
# Index Page
#---------------------------
index: 
  banner_img: https://csidezyum.oss-cn-hangzhou.aliyuncs.com/owncloud/index.jpg?Expires=1577780860&OSSAccessKeyId=TMP.hjKfK72cJN4XjkW3vp2EC6gdNQJK64XcRhTuYDawXdzfpW6jKtCdHymyoSVN4UN6MjZkZ4Phz22puhtw18i5fCivjzChhu3SerHw3YKtWhcp4qA4d1rJMPhFuU8NUP.tmp&Signature=%2FGNiWKMVE%2Bisqq7AE7COuXKQaS8%3D
  banner_img_height: 80  # available: 0 - 100
  subtitle:
    enable: true
  auto_excerpt:
    enable: true
    length: 120
  post_url_target: _self  # available: _blank | _self
  post_info:
    enable: true


#---------------------------
# 导航栏
# Head Navbar
#---------------------------
navbar:
  menu:
    Home: /
    Archives: /archives/
    About: /about/


#---------------------------
# 文章页
# Post Page
#---------------------------
post: 
  banner_img: /post.jpg
  banner_img_height: 70  # available: 0 - 100
  toc: 
    enable: true
  highlight:
    enable: true
    theme: github # available: github | tomorrow | tomorrow-night | tomorrow-night-eighties
  copyright:
    enable: true
    content: 本博客所有文章除特别声明外，均采用 <a href="https://zh.wikipedia.org/wiki/Wikipedia:CC_BY-SA_3.0%E5%8D%8F%E8%AE%AE%E6%96%87%E6%9C%AC">CC BY-SA 3.0协议</a> 。转载请注明出处！
  comments: 
    enable: true
    type: disqus  # available: disqus | valine

# Disqus
disqus:
  shortname: csidez # your shortname
  count: true
  
# Valine
# You can get your appid and appkey from https://leancloud.cn
# More info available at https://valine.js.org
valine:
  enable: false # When enable is set to be true, leancloud_visitors is recommended to be closed for the re-initialization problem within different leancloud adk version.
  appid:  # your leancloud application appid
  appkey:  # your leancloud application appkey
  notify: false # mail notifier, See: https://github.com/xCss/Valine/wiki
  verify: false # Verification code
  placeholder: 说点什么 # comment box placeholder
  avatar: retro # gravatar style https://valine.js.org/avatar.html
  pageSize: 10 # pagination size
  visitor: false # leancloud-counter-security is not supported for now. When visitor is set to be true, appid and appkey are recommended to be the same as leancloud_visitors' for counter compatibility. Article reading statistic https://valine.js.org/visitor.html


#---------------------------
# 归档页
# Archive Page
#---------------------------
archive: 
  banner_img: /archive.jpg
  banner_img_height: 80  # available: 0 - 100

# https://imgur.com/SaGvNcE
#---------------------------
# 关于页
# About Page
#---------------------------
about:
  banner_img: /about.jpg
  banner_img_height: 80  # available: 0 - 100
  avatar: /user.png
  name: csidez
  introduce: 道不同不相为谋，人各有志“雁南飞”
  icons: 
    github: https://github.com/HaloCsidez
    twitter: https://twitter.com/HaloCsidez
    weibo: https://weibo.com/u/5246731009

# 懒加载
lazyload:
  enable: true
  # className: #可选 e.g. .J-lazyload-img
  # loadingImg: #可选 eg. ./images/loading.png
